* fll_fstab_generator:   - use error=remount-ro mount option for ext2 and ext3 / filesystem   - use ID_FS_LABEL_SAFE returned by udev_info() as third argument to     print_fsentry()   - use a temporary directory to maintain uniquity and sanity of any string     to be used in fs_spec and fs_file   - check value returned by sed call in is_mounted() is actually a directory     before returning it   - if labels are wanted, use the "safe" label in fs_file

diff --git a/bin/fll_fstab_generator b/bin/fll_fstab_generator
--- a/bin/fll_fstab_generator
+++ b/bin/fll_fstab_generator
@@ -174,7 +174,7 @@ is_mounted()
 
 	for d in ${@}; do
 		mntpnt=$(sed -n "s%^/dev/${d} \([^[:space:]]\+\).*%\1%p" /proc/mounts | head -n1)
-		if [ "${mntpnt}" ]; then
+		if [ -d "${mntpnt}" ]; then
 			echo "${mntpnt}"
 			break
 		fi
@@ -226,35 +226,72 @@ _printf_mntent()
 }
 
 #
+# create state directory
+#
+set -e
+FSTAB_STATE_DIR=$(mktemp -p /tmp -d fstab.XXXX)
+trap "{
+	if [ -d \"${FSTAB_STATE_DIR}\" ]; then
+		find \"${FSTAB_STATE_DIR}\" -delete
+	fi
+}" EXIT
+set +e
+
+#
+# utility to store state of unique fsentry attributes
+#
+record_state_of()
+{
+	if [ "${#}" -eq 1 ] && mkdir "${FSTAB_STATE_DIR}/${1}"; then
+		return 0
+	elif [ -d "${FSTAB_STATE_DIR}/${1}" ]; then
+		warn "already recorded state of: ${1}"
+		warn "${1} is not unique"
+	else
+		warn "failed to record state of: ${*}"
+		warn "${*} is invalid"
+	fi
+
+	return 1
+}
+
+#
 # print fstab entry for a filesystem
 #
 print_fsentry()
 {
 	local fs_spec fs_file fs_vfstype fs_mntops fs_freq fs_passno
-	local name type symlinks label uuid mounted part
+	local symlinks label uuid part
+
+	local name type label_safe
 	name="${1}"
 	type="${2}"
+	label_safe="${3}"
+
+	local mounted label_is_safe_and_sound
 	mounted=false
+	label_is_safe_and_sound=false
 
 	case "${name}" in
 		mapper/*)
 			type=$(udev_volid type /dev/${name})
 			label=$(udev_volid label /dev/${name})
+			label_safe="${label}"
 			uuid=$(udev_volid uuid /dev/${name})
 			;;
 		*)
 			symlinks=$(disk_symlinks ${name})
 
-			for s in ${symlinks}; do
-				[ -L "/dev/${s}" ] || continue
-				dbg "${s}"
+			for symlink in ${symlinks}; do
+				[ -L "/dev/${symlink}" ] || continue
+				dbg "${symlink}"
 
-				case "${s}" in
+				case "${symlink}" in
 					disk/by-label/*)
-						label="${s##*/}"
+						label="${symlink#disk/by-label/}"
 						;;
 					disk/by-uuid/*)
-						uuid="${s##*/}"
+						uuid="${symlink#disk/by-uuid/}"
 						;;
 				esac
 			done
@@ -265,13 +302,15 @@ print_fsentry()
 	# fs_spec - first field describes the block special device or remote
 	#           filesystem to be mounted
 	#
-	if ${OPT_LABELS} && [ "${label}" ]; then
+	if ${OPT_LABELS} && record_state_of "${label_safe}"; then
+		label_is_safe_and_sound=:
+
 		if is_nativefs "${type}"; then
 			fs_spec="LABEL=${label}"
 		else
 			fs_spec="/dev/disk/by-label/${label}"
 		fi
-	elif ${OPT_UUIDS} && [ "${uuid}" ]; then
+	elif ${OPT_UUIDS} && record_state_of "${uuid}"; then
 		if is_nativefs "${type}"; then
 			fs_spec="UUID=${uuid}"
 		else
@@ -292,27 +331,36 @@ print_fsentry()
 		dbg "${name} is mounted on ${fs_file}"
 		mounted=:
 	elif [ "${type}" = "swap" ]; then
-		fs_file="none"
-
 		if ${OPT_NOSWAP}; then
+			dbg "ignoring swap partition"
 			return
+		else
+			fs_file="none"
 		fi
+	elif ${label_is_safe_and_sound}; then
+		fs_file="/media/${label_safe}"
 	else
 		case "${name}" in
 			mapper/*)
-				fs_file="/media/${name#mapper/}"
+				fs_file="${name#mapper/}"
 				;;
 			*)
 				part=$(echo ${name} | egrep -o '[[:digit:]]+$')
 				
 				if [ "${part}" ]; then
-					fs_file="/media/disk${disk}part${part}"
+					fs_file="disk${disk}part${part}"
 				else
 					dbg "partition index invalid"
 					continue
 				fi
 				;;
 		esac
+
+		if record_state_of "${fs_file}"; then
+			fs_file="/media/${fs_file}"
+		else
+			return
+		fi
 	fi
 
 	#
@@ -353,6 +401,13 @@ print_fsentry()
 					case "${fs_file}" in
 						/media/*)
 							fs_mntops="${fs_mntops},rw,exec,noatime"
+							;;
+						/)
+							if [ "${type}" = "ext2" ] || [ "${type}" = "ext3" ]; then
+								fs_mntops="errors=remount-ro,noatime"
+							else
+								fs_mntops="defaults,noatime"
+							fi
 							;;
 						*)
 							fs_mntops="defaults,noatime"
@@ -416,10 +471,11 @@ scan_partitions()
 		[ -d "${p}" ] || continue
 		name=${p##*/}
 
-		unset ID_FS_TYPE ID_FS_USAGE
+		unset ID_FS_TYPE ID_FS_USAGE ID_FS_LABEL_SAFE
 
 		eval "$(disk_env ${name} | grep -e '^ID_FS_TYPE=' \
-						-e '^ID_FS_USAGE=')"
+						-e '^ID_FS_USAGE=' \
+						-e '^ID_FS_LABEL_SAFE=')"
 
 		dbg "sysfs path: ${p}"
 		dbg "ID_FS_TYPE=${ID_FS_TYPE} ID_FS_USAGE=${ID_FS_USAGE}"
@@ -430,7 +486,7 @@ scan_partitions()
 			continue
 		fi
 
-		print_fsentry "${name}" "${ID_FS_TYPE}"
+		print_fsentry "${name}" "${ID_FS_TYPE}" "${ID_FS_LABEL_SAFE}"
 	done
 }
 
