* fll-cpufreq: don't allow restart|force-reload.

diff --git a/debian/fll-live-initscripts.fll-cpufreq.init b/debian/fll-live-initscripts.fll-cpufreq.init
--- a/debian/fll-live-initscripts.fll-cpufreq.init
+++ b/debian/fll-live-initscripts.fll-cpufreq.init
@@ -210,9 +210,8 @@ case "${1}" in
 	stop)
 		;;
 	restart|force-reload)
-		${0} stop
-        	sleep 1
-		${0} start
+		echo "Error: argument '${1}' not supported" >&2
+		exit 3
 		;;
 	*)
 		echo "Usage: ${NAME} {start|stop|restart|force-reload}" >&2
